// Code generated by hertz generator.

package api

import (
	"context"
	"memogo/biz/dal/db"
	"memogo/biz/dal/repository"
	"memogo/biz/model/memogo/api"
	"memogo/biz/service"
	"memogo/pkg/middleware"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ListTodos .
// @router /v1/todos [GET]
func ListTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListTodosReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.ListTodosResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	statusStr := strings.ToLower(req.GetStatus())
	page := int(req.GetPage())
	pageSize := int(req.GetPageSize())

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)

	items, total, err := todoSvc.ListTodos(userID, statusStr, page, pageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.ListTodosResp{Status: 500, Msg: "List failed: " + err.Error()})
		return
	}

	apiItems := make([]*api.Todo, 0, len(items))
	for _, t := range items {
		at := &api.Todo{
			ID:        int64(t.ID),
			Title:     t.Title,
			Content:   t.Content,
				Status:    api.TodoStatus(t.Status),
			CreatedAt: t.CreatedAt.Unix(),
		}
		if t.StartTime != nil {
			at.StartTime = t.StartTime.Unix()
		}
		if t.EndTime != nil {
			at.EndTime = t.EndTime.Unix()
		}
		if t.DueTime != nil {
			at.DueTime = t.DueTime.Unix()
		}
		apiItems = append(apiItems, at)
	}

	c.JSON(consts.StatusOK, &api.ListTodosResp{
		Status: 200,
		Msg:    "ok",
		Data: &api.ItemsTodoData{
			Items: apiItems,
			Total: total,
		},
	})
}

// SearchTodos .
// @router /v1/todos/search [GET]
func SearchTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchTodosReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.SearchTodosResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	q := req.GetQ()
	page := int(req.GetPage())
	pageSize := int(req.GetPageSize())

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)
	items, total, err := todoSvc.SearchTodos(userID, q, page, pageSize)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.SearchTodosResp{Status: 500, Msg: "Search failed: " + err.Error()})
		return
	}

	apiItems := make([]*api.Todo, 0, len(items))
	for _, t := range items {
		at := &api.Todo{
			ID:        int64(t.ID),
			Title:     t.Title,
			Content:   t.Content,
				Status:    api.TodoStatus(t.Status),
			CreatedAt: t.CreatedAt.Unix(),
		}
		if t.StartTime != nil {
			at.StartTime = t.StartTime.Unix()
		}
		if t.EndTime != nil {
			at.EndTime = t.EndTime.Unix()
		}
		if t.DueTime != nil {
			at.DueTime = t.DueTime.Unix()
		}
		apiItems = append(apiItems, at)
	}

	c.JSON(consts.StatusOK, &api.SearchTodosResp{
		Status: 200,
		Msg:    "ok",
		Data: &api.ItemsTodoData{
			Items: apiItems,
			Total: total,
		},
	})
}

// ListTodosCursor .
// @router /v1/todos/cursor [GET]
func ListTodosCursor(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListTodosCursorReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 获取用户 ID
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.ListTodosCursorResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	statusStr := strings.ToLower(req.GetStatus())
	cursor := uint(req.GetCursor())
	limit := int(req.GetLimit())

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)

	items, nextCursor, hasMore, err := todoSvc.ListTodosCursor(userID, statusStr, cursor, limit)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.ListTodosCursorResp{Status: 500, Msg: "Query failed: " + err.Error()})
		return
	}

	// 转换为 API 模型
	apiItems := make([]*api.Todo, 0, len(items))
	for _, t := range items {
		at := &api.Todo{
			ID:        int64(t.ID),
			Title:     t.Title,
			Content:   t.Content,
				Status:    api.TodoStatus(t.Status),
			CreatedAt: t.CreatedAt.Unix(),
		}
		if t.StartTime != nil {
			at.StartTime = t.StartTime.Unix()
		}
		if t.EndTime != nil {
			at.EndTime = t.EndTime.Unix()
		}
		if t.DueTime != nil {
			at.DueTime = t.DueTime.Unix()
		}
		apiItems = append(apiItems, at)
	}

	c.JSON(consts.StatusOK, &api.ListTodosCursorResp{
		Status: 200,
		Msg:    "ok",
		Data: &api.CursorTodoData{
			Items:      apiItems,
			NextCursor: int64(nextCursor),
			HasMore:    hasMore,
		},
	})
}

// SearchTodosCursor .
// @router /v1/todos/search/cursor [GET]
func SearchTodosCursor(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchTodosCursorReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 获取用户 ID
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.SearchTodosCursorResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	keyword := req.GetQ()
	cursor := uint(req.GetCursor())
	limit := int(req.GetLimit())

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)

	items, nextCursor, hasMore, err := todoSvc.SearchTodosCursor(userID, keyword, cursor, limit)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.SearchTodosCursorResp{Status: 500, Msg: "Search failed: " + err.Error()})
		return
	}

	// 转换为 API 模型
	apiItems := make([]*api.Todo, 0, len(items))
	for _, t := range items {
		at := &api.Todo{
			ID:        int64(t.ID),
			Title:     t.Title,
			Content:   t.Content,
				Status:    api.TodoStatus(t.Status),
			CreatedAt: t.CreatedAt.Unix(),
		}
		if t.StartTime != nil {
			at.StartTime = t.StartTime.Unix()
		}
		if t.EndTime != nil {
			at.EndTime = t.EndTime.Unix()
		}
		if t.DueTime != nil {
			at.DueTime = t.DueTime.Unix()
		}
		apiItems = append(apiItems, at)
	}

	c.JSON(consts.StatusOK, &api.SearchTodosCursorResp{
		Status: 200,
		Msg:    "ok",
		Data: &api.CursorTodoData{
			Items:      apiItems,
			NextCursor: int64(nextCursor),
			HasMore:    hasMore,
		},
	})
}
