// Code generated by hertz generator.

package api

import (
	"context"
	"errors"
	"memogo/biz/dal/db"
	"memogo/biz/dal/repository"
	"memogo/biz/model/memogo/api"
	"memogo/biz/service"
	"memogo/pkg/middleware"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateTodo .
// @router /v1/todos [POST]
func CreateTodo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateTodoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 从 JWT 中间件获取用户 ID
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.CreateTodoResp{
			Status: 401,
			Msg:    "Unauthorized: " + err.Error(),
		})
		return
	}

	// 组装服务并创建 Todo
	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)

	// 可选时间字段转换（秒 → time.Time）
	var startPtr, duePtr *time.Time
	if req.IsSetStartTime() {
		t := time.Unix(req.GetStartTime(), 0)
		startPtr = &t
	}
	if req.IsSetDueTime() {
		t := time.Unix(req.GetDueTime(), 0)
		duePtr = &t
	}

	todo, err := todoSvc.Create(userID, req.GetTitle(), req.GetContent(), startPtr, duePtr)
	if err != nil {
		// 参数错误 → 400，其它错误 → 500
		status := consts.StatusInternalServerError
		msg := "Create todo failed: " + err.Error()
		if errors.Is(err, service.ErrTitleRequired) || errors.Is(err, service.ErrContentRequired) {
			status = consts.StatusBadRequest
		}
		c.JSON(status, &api.CreateTodoResp{Status: int32(status), Msg: msg})
		return
	}

	// 转为 API 模型
	respTodo := &api.Todo{
		ID:        int64(todo.ID),
		Title:     todo.Title,
		Content:   todo.Content,
		View:      int32(todo.View),
		Status:    api.TodoStatus(todo.Status),
		CreatedAt: todo.CreatedAt.Unix(),
	}
	if todo.StartTime != nil {
		respTodo.StartTime = todo.StartTime.Unix()
	}
	if todo.EndTime != nil {
		respTodo.EndTime = todo.EndTime.Unix()
	}
	if todo.DueTime != nil {
		respTodo.DueTime = todo.DueTime.Unix()
	}

	c.JSON(consts.StatusOK, &api.CreateTodoResp{
		Status: 200,
		Msg:    "ok",
		Data:   respTodo,
	})
}

// UpdateTodoStatus .
// @router /v1/todos/:id/status [PATCH]
func UpdateTodoStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateTodoStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	// 认证
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.UpdateTodoStatusResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)

	affected, err := todoSvc.UpdateTodoStatus(userID, uint(req.GetID()), int32(req.GetStatus()))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.UpdateTodoStatusResp{Status: 500, Msg: "Update failed: " + err.Error()})
		return
	}
	c.JSON(consts.StatusOK, &api.UpdateTodoStatusResp{Status: 200, Msg: "ok", Data: int32(affected)})
}

// UpdateAllStatus .
// @router /v1/todos/status [PATCH]
func UpdateAllStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateAllStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.UpdateAllStatusResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)

	affected, err := todoSvc.UpdateAllStatus(userID, int32(req.GetFromStatus()), int32(req.GetToStatus()))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.UpdateAllStatusResp{Status: 500, Msg: "Update failed: " + err.Error()})
		return
	}
	c.JSON(consts.StatusOK, &api.UpdateAllStatusResp{Status: 200, Msg: "ok", Data: int32(affected)})
}

// DeleteOne .
// @router /v1/todos/:id [DELETE]
func DeleteOne(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteOneReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.DeleteResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)
	affected, err := todoSvc.DeleteOne(userID, uint(req.GetID()))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.DeleteResp{Status: 500, Msg: "Delete failed: " + err.Error()})
		return
	}
	c.JSON(consts.StatusOK, &api.DeleteResp{Status: 200, Msg: "ok", Data: int32(affected)})
}

// DeleteByScope .
// @router /v1/todos [DELETE]
func DeleteByScope(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteByScopeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.DeleteResp{Status: 401, Msg: "Unauthorized: " + err.Error()})
		return
	}

	scope := strings.ToLower(req.GetScope())
	if scope != "done" && scope != "todo" && scope != "all" {
		c.JSON(consts.StatusBadRequest, &api.DeleteResp{Status: 400, Msg: "invalid scope"})
		return
	}

	todoRepo := repository.NewTodoRepository(db.DB)
	todoSvc := service.NewTodoService(todoRepo)
	affected, err := todoSvc.DeleteByScope(userID, scope)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, &api.DeleteResp{Status: 500, Msg: "Delete failed: " + err.Error()})
		return
	}
	c.JSON(consts.StatusOK, &api.DeleteResp{Status: 200, Msg: "ok", Data: int32(affected)})
}
